import { NavBar } from "./components";
import "./globals.css";
export const metadata = {
  title: "Yoga App",
  description: "Generated by Deepanshu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <NavBar />
        <main className="my-container bg-orange-100">{children}</main>
      </body>
    </html>
  );
}
